services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    hostname: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - whoiswho:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  springboot-app1:
    build: .
    depends_on:
      - postgres
      # - rabbitmq
    ports:
      - 8080:8080
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  backend-ws:
    build: ../whoiswho-ws/
    ports:
      - 3000:3000
    depends_on:
      - postgres
    env_file:
      - ../whoiswho-ws/.env
  
  # angular-app:
  #   build: ../whoiswho-app/
  #   ports:
  #     - 4200:4200
  #   depends_on:
  #     - springboot-app1
  #     - backend-ws
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '0.5GB'

  # springboot-app2:
  #   extends:
  #     service: springboot-app1

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - springboot-app1
  #     - springboot-app2
  #   ports:
  #     - '8080:443'
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./selfsigned.crt:/etc/nginx/selfsigned.crt
  #     - ./selfsigned.key:/etc/nginx/selfsigned.key
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: '0.5GB'

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   hostname: rabbitmq
  #   ports:
  #     # - "5672:5672"     
  #     # - "15672:15672"
  #     - "61613:61613"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #   restart: always
  #   command: >
  #     bash -c "rabbitmq-plugins enable rabbitmq_stomp &&
  #              rabbitmq-plugins enable rabbitmq_web_stomp &&
  #              rabbitmq-server"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: '0.5GB'

volumes:
  whoiswho:
