services:
  mysql:
    image: mysql:latest
    hostname: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app1:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  springboot-app2:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

  nginx:
    image: nginx:latest
    depends_on:
      - springboot-app1
      - springboot-app2
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_stomp &&
               rabbitmq-plugins enable rabbitmq_web_stomp &&
               rabbitmq-server"
  # redis:
  #   image: redis
  #   hostname: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '0.5GB'

volumes:
  mysql-data:
