services:
  mysql:
    image: mysql:latest
    hostname: mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  springboot-app1:
    build: .
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

      API_SECURITY_TOKEN_SECRET: ${API_SECURITY_TOKEN_SECRET}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  springboot-app2:
    extends:
      service: springboot-app1

  nginx:
    image: nginx:latest
    depends_on:
      - springboot-app1
      - springboot-app2
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      # - "5672:5672"     
      # - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    restart: always
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_stomp &&
               rabbitmq-plugins enable rabbitmq_web_stomp &&
               rabbitmq-server"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

volumes:
  mysql-data:
