services:
  mysql:
    image: mysql:latest
    hostname: mysql
    environment:
      - 'MYSQL_DATABASE=whoiswho'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=user'
    ports:
      - '3307:3306'
    volumes:
      - mysql-data:/var/lib/mysql

  springboot-app:
    build: .
    depends_on:
      - mysql
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/whoiswho
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql-data:
